Traceback (most recent call last):
  File "/home/ian/mambaforge/envs/voters/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/ian/mambaforge/envs/voters/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ian/mambaforge/envs/voters/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ian/mambaforge/envs/voters/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ian/mambaforge/envs/voters/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/ian/mambaforge/envs/voters/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/ian/mambaforge/envs/voters/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, axs = multi_year_bar(age_grouped, turnout_bar_graph, years_per_row=3, figsize=(16,8))
fig.supxlabel("Age (4 year bins)")
fig.supylabel("Number of voters")
fig.suptitle(
axs[-1][-1].legend()
axs[-1,-1].set_xlim([17.5, 85])
plt.tight_layout();
# plt.tight_layout()
------------------


[0;36m  Cell [0;32mIn[4], line 4[0;36m[0m
[0;31m    fig.suptitle([0m
[0m                ^[0m
[0;31mSyntaxError[0m[0;31m:[0m '(' was never closed


